version: '3'
services:
 todofrontend:
    build:
      context: ./client/typetodo
      dockerfile: Dockerfile.client
    ports:  
      - "5173:5173" 
    depends_on:
      - todobackend

 todobackend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:  
      - "5000:5000" 
      