FROM node:18-alpine

# update packages
# RUN apk update

# create root application folder
WORKDIR /app

# copy configs to /app folder
COPY package*.json ./
COPY tsconfig.json ./
COPY tsconfig.node.json ./
COPY index.html ./
COPY vite.config.ts ./
COPY tsconfig.node.json ./
# copy source code to /app/src folder
COPY src /app/src

# check files list
RUN ls -a

RUN npm install


EXPOSE 5173


CMD ["npm","run","dev"]